language: ruby
dist: xenial

# === travis build limitations
# blocklist
branches:
  except:
  - master

# === setup install & build
cache: bundler

before_install:
  - gem update --system
  - gem install rake
  - gem install bundler

install:
  - bundle install
  - git submodule update --remote --recursive

before_script:
    - rm -rfv _site

script:
    # build site
    - bundle exec jekyll build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:  # deployment limitations
    branch: src
  target_branch: master

  local_dir: _site
  # fqdn: travis-blogdown.yihui.name  # this sets CNAME for custom DN
  keep_history: true

notifications:
  email:
    recipients:
    - tylarmurray@mail.usf.edu.com
    on_success: never
    on_failure: change
